app:
    resource: @WallabagCoreBundle/Controller/
    type:     annotation

homepage:
    pattern:   /
    defaults:  { _controller: WallabagCoreBundle:Entry:showUnread }

doc-api:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc

#login:
#    pattern:   /login
#    defaults:  { _controller: WallabagCoreBundle:Security:login }
#login_check:
#    pattern:   /login_check
logout:
    path:   /logout

rest :
  type : rest
  resource : "@WallabagApiBundle/Resources/config/routing_rest_v1.yml"
  prefix : /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

wallabag_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: WallabagCoreBundle:Security:login }

wallabag_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: WallabagCoreBundle:Security:loginCheck }
